// 



import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FormProvider, UsersProvider, ThemeProvider } from "./assets/contexts";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      // lang="ar"
      // dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-transparent text-slate-900 antialiased">
        <ThemeProvider>
          <UsersProvider>
            <FormProvider>
              {/* 🔹 مكون الهيدر / السايدبار يلتف حول المحتوى */}
              <Header>{children}</Header>
            </FormProvider>
          </UsersProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}